/*CONSULTA 1*/
SELECT CNT.NAME, 
	LGG.LANGUAGE, 
	LGG.PERCENTAGE 
FROM LANGUAGES LGG, 
	COUNTRIES CNT 
WHERE LGG.LANGUAGE = 'Slovene' 
AND LGG.COUNTRY_CODE = CNT.CODE 
ORDER BY LGG.PERCENTAGE DESC;

/*CONSULTA 2*/
SELECT CNT.NAME AS NOMBRE_PAIS,
	LGG.LANGUAGE AS IDIOMA,
    (SELECT COUNT(CTT.COUNTRY_CODE) 
		FROM CITIES CTT 
        WHERE CTT.COUNTRY_CODE = CNT.CODE) AS TOTAL_CIUDADES
FROM COUNTRIES CNT,
    LANGUAGES LGG
WHERE CNT.CODE = LGG.COUNTRY_CODE
ORDER BY TOTAL_CIUDADES DESC;

/*CONSULTA 3*/
SELECT *
FROM CITIES 
WHERE COUNTRY_CODE = 'MEX'
AND POPULATION > 500000
ORDER BY POPULATION DESC;

/*CONSULTA 4*/
SELECT CNT.NAME AS NOMBRE_PAIS,
	LGG.LANGUAGE AS IDIOMA,
    LGG.PERCENTAGE AS PORCENTAJE
FROM COUNTRIES CNT,
	LANGUAGES LGG
WHERE CNT.CODE = LGG.COUNTRY_CODE
AND LGG.PERCENTAGE > 89
ORDER BY PORCENTAJE DESC;

/*CONSULTA 5*/
SELECT *
FROM COUNTRIES
WHERE SURFACE_AREA < 501
AND POPULATION > 100000;

/*CONSULTA 6*/
SELECT * 
FROM COUNTRIES
WHERE GOVERNMENT_FORM = 'Constitutional Monarchy'
AND CAPITAL > 200
AND LIFE_EXPECTANCY > 75;

/*CONSULTA 7*/
SELECT CNT.NAME,
	CTT.NAME,
    CTT.DISTRICT,
    CTT.POPULATION
FROM CITIES CTT,
	COUNTRIES CNT
WHERE CTT.COUNTRY_CODE = 'ARG'
AND CTT.COUNTRY_CODE = CNT.CODE
AND CTT.DISTRICT = 'Buenos Aires'
AND CTT.POPULATION > 500000;

/*CONSULTA 8*/
SELECT REGION,
	COUNT(NAME) AS NUMERO_DE_PAISES
FROM COUNTRIES
GROUP BY REGION
ORDER BY NUMERO_DE_PAISES DESC;